name: Cloud_Computing_Project

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  check_service:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
      - run: uv --version
      - name: Install dependencies
        run: uv sync
      - name: Build Project
        run: uv build
      - name: Running unit tests
        run: uv run pytest tests/

  build_docker_image:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
      - run: uv sync
      - name: Build Docker Image
        run: |
          echo "Building Docker image after PR merge"

  deploy_service_on_azure:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: yezz123/setup-uv@v4
      - run: uv sync
      - name: Deploy Service on Azure
        run: |
          echo "Deploying service on Azure after PR merge"
